version: 2

updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 8
    groups:
      pest-development-stack:
        patterns:
          - pestphp/*
          - phpunit/phpunit
          - nunomaduro/collision
      production-patch-and-minor:
        dependency-type: production
        update-types:
          - patch
          - minor
      development-patch-and-minor:
        dependency-type: development
        exclude-patterns:
          - pestphp/*
          - phpunit/phpunit
          - nunomaduro/collision
        update-types:
          - patch
          - minor

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:15"
      timezone: Europe/Berlin
    open-pull-requests-limit: 8
    groups:
      npm-patch-and-minor:
        patterns:
          - "*"
        update-types:
          - patch
          - minor

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:45"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
