name: 'Build assets'
description: 'Setup Node.js, install dependencies, and build assets'
inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js (from .node-version)
      if: ${{ inputs.node-version == '' }}
      uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'
        cache: 'npm'
    - name: Setup Node.js (explicit)
      if: ${{ inputs.node-version != '' }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
    - run: npm ci
      shell: bash
    - run: npm run build
      shell: bash
