<?php

use App\Enums\Role;
use App\Models\Poll;

return [
    'auth' => [
        [
            'layout' => 'featured',
            'title' => 'Dashboard',
            'route' => 'dashboard',
            'tour_key' => 'dashboard',
            'icon' => 'o-home',
            'active_patterns' => ['dashboard'],
        ],
        [
            'layout' => 'featured',
            'title' => 'Aktuelle Veranstaltung',
            'route' => 'veranstaltungen.aktuell',
            'tour_key' => 'current-event',
            'icon' => 'o-calendar-days',
            'active_patterns' => ['veranstaltungen.*', 'fantreffen.2026*'],
            'accent' => true,
        ],
        [
            'layout' => 'featured',
            'title' => 'Aktuelle Umfrage',
            'route' => 'umfrage.aktuell',
            'tour_key' => 'active-poll',
            'icon' => 'o-chart-bar',
            'active_patterns' => ['umfrage.aktuell'],
            'visibility_flag' => 'showActivePollForAuth',
            'label_context_key' => 'activePollMenuLabel',
        ],
        [
            'layout' => 'section',
            'title' => 'Community',
            'tour_key' => 'section-community',
            'icon' => 'o-user-group',
            'items' => [
                ['title' => 'Mitgliederliste', 'route' => 'mitglieder.index', 'tour_key' => 'community-members', 'icon' => 'o-users'],
                ['title' => 'Mitgliederkarte', 'route' => 'mitglieder.karte', 'tour_key' => 'community-map', 'icon' => 'o-map-pin'],
                [
                    'title' => 'Cover-Bewertungen',
                    'route' => 'cover-ratings.index',
                    'tour_key' => 'community-cover-ratings',
                    'active_patterns' => ['cover-ratings.*'],
                    'icon' => 'o-photo',
                    'config_enabled' => 'cover-ratings.enabled',
                ],
                ['title' => 'Rezensionen', 'route' => 'reviews.index', 'tour_key' => 'community-reviews', 'icon' => 'o-star'],
                ['title' => 'Fanfiction', 'route' => 'fanfiction.index', 'tour_key' => 'community-fanfiction', 'icon' => 'o-pencil-square'],
                ['title' => 'Tauschbörse', 'route' => 'romantausch.index', 'tour_key' => 'community-swap', 'icon' => 'o-arrows-right-left'],
                ['title' => 'Auktionen', 'route' => 'auktionen.index', 'tour_key' => 'community-auctions', 'icon' => 'o-banknotes'],
            ],
        ],
        [
            'layout' => 'section',
            'title' => 'Inhalte',
            'tour_key' => 'section-content',
            'icon' => 'o-sparkles',
            'items' => [
                ['title' => 'Maddraxiversum', 'route' => 'maddraxiversum.index', 'tour_key' => 'content-maddraxiversum', 'icon' => 'o-globe-europe-africa'],
                ['title' => 'Kompendium', 'route' => 'kompendium.index', 'tour_key' => 'content-kompendium', 'icon' => 'o-book-open'],
                ['title' => 'Downloads', 'route' => 'downloads', 'tour_key' => 'content-downloads', 'icon' => 'o-arrow-down-tray'],
                ['title' => '3D-Modelle', 'route' => '3d-modelle.index', 'tour_key' => 'content-3d-models', 'icon' => 'o-cube'],
                ['title' => 'Statistik', 'route' => 'statistik.index', 'tour_key' => 'content-stats', 'icon' => 'o-chart-bar-square'],
            ],
        ],
        [
            'layout' => 'section',
            'title' => 'Veranstaltungen',
            'tour_key' => 'section-events',
            'icon' => 'o-calendar',
            'items' => [
                ['title' => 'Fotos', 'route' => 'fotogalerie', 'tour_key' => 'events-photos', 'icon' => 'o-photo'],
                ['title' => 'Meetings', 'route' => 'meetings', 'tour_key' => 'events-meetings', 'icon' => 'o-video-camera'],
                ['title' => 'Termine', 'route' => 'termine', 'tour_key' => 'events-dates', 'icon' => 'o-calendar-days'],
            ],
        ],
        [
            'layout' => 'section',
            'title' => 'Verein',
            'tour_key' => 'section-club',
            'icon' => 'o-building-office-2',
            'items' => [
                ['title' => 'Newsletter-Archiv', 'route' => 'newsletter.archiv.index', 'tour_key' => 'club-newsletters', 'icon' => 'o-envelope-open'],
                ['title' => 'Protokolle', 'route' => 'protokolle', 'tour_key' => 'club-minutes', 'icon' => 'o-document-text'],
                ['title' => 'Satzung', 'route' => 'satzung', 'tour_key' => 'club-bylaws', 'icon' => 'o-scale'],
                ['title' => 'Kassenstand', 'route' => 'kassenstand.index', 'tour_key' => 'club-balance', 'icon' => 'o-banknotes'],
            ],
        ],
        [
            'layout' => 'section',
            'title' => 'Baxx',
            'tour_key' => 'section-baxx',
            'icon' => 'o-bolt',
            'items' => [
                ['title' => 'Baxx verdienen', 'route' => 'todos.index', 'tour_key' => 'baxx-todos', 'icon' => 'o-bolt'],
                ['title' => 'Belohnungen einlösen', 'route' => 'rewards.index', 'tour_key' => 'baxx-rewards', 'icon' => 'o-gift'],
            ],
        ],
        [
            'layout' => 'section',
            'title' => 'Teams & AG',
            'tour_key' => 'section-teams',
            'icon' => 'o-rectangle-group',
            'visible_any' => [
                ['vorstand' => true],
                ['has_non_personal_team' => true],
            ],
            'items' => [
                [
                    'title' => 'EARDRAX Dashboard',
                    'route' => 'hoerbuecher.index',
                    'tour_key' => 'teams-hoerbuecher',
                    'icon' => 'o-speaker-wave',
                    'visible_any' => [
                        ['vorstand' => true],
                        ['team_any' => ['AG Fanhörbücher']],
                    ],
                ],
                [
                    'title' => 'Kompendium',
                    'route' => 'kompendium.index',
                    'tour_key' => 'teams-kompendium',
                    'icon' => 'o-book-open',
                    'team_any' => ['AG Maddraxikon'],
                ],
                [
                    'title' => 'AG verwalten',
                    'route' => 'ag.index',
                    'tour_key' => 'teams-manage',
                    'icon' => 'o-user-group',
                    'has_non_personal_owned_team' => true,
                ],
                [
                    'title' => 'Charakter-Editor',
                    'route' => 'rpg.char-editor',
                    'tour_key' => 'teams-char-editor',
                    'icon' => 'o-pencil-square',
                    'visible_any' => [
                        ['team_any' => ['AG Rollenspiel']],
                        ['mitglieder_roles_any' => [Role::Admin]],
                    ],
                ],
            ],
        ],
        [
            'layout' => 'section',
            'title' => 'Vorstand',
            'tour_key' => 'section-board',
            'icon' => 'o-shield-check',
            'visible_any' => [
                ['roles_any' => [Role::Admin, Role::Vorstand, Role::Kassenwart]],
                ['veranstaltungsverwaltung' => true],
            ],
            'items' => [
                ['title' => 'Kassenbuch', 'route' => 'kassenbuch.index', 'tour_key' => 'board-ledger', 'icon' => 'o-banknotes', 'roles_any' => [Role::Admin, Role::Vorstand, Role::Kassenwart]],
                ['title' => 'Auktionen', 'route' => 'admin.auktionen.index', 'tour_key' => 'board-auctions', 'icon' => 'o-scale', 'roles_any' => [Role::Admin, Role::Vorstand, Role::Kassenwart]],
                ['title' => 'Statistik', 'route' => 'admin.statistiken.index', 'tour_key' => 'board-stats', 'icon' => 'o-chart-bar-square', 'roles_any' => [Role::Admin, Role::Vorstand, Role::Kassenwart]],
                ['title' => 'Veranstaltungen', 'route' => 'admin.veranstaltungen.index', 'tour_key' => 'board-events', 'icon' => 'o-calendar-days', 'veranstaltungsverwaltung' => true],
                ['title' => 'Fanfiction', 'route' => 'admin.fanfiction.index', 'tour_key' => 'board-fanfiction', 'icon' => 'o-pencil-square', 'roles_any' => [Role::Admin, Role::Vorstand, Role::Kassenwart]],
                ['title' => 'Touren', 'route' => 'admin.touren.index', 'tour_key' => 'board-tours', 'icon' => 'o-map', 'roles_any' => [Role::Admin, Role::Vorstand]],
                ['title' => 'Newsletter versenden', 'route' => 'newsletter.create', 'tour_key' => 'admin-newsletter', 'icon' => 'o-envelope', 'roles_any' => [Role::Admin, Role::Vorstand]],
                ['title' => 'Umfrage verwalten', 'route' => 'admin.umfragen.index', 'tour_key' => 'board-polls', 'icon' => 'o-chart-bar', 'roles_any' => [Role::Admin, Role::Vorstand, Role::Kassenwart], 'can' => ['manage', Poll::class]],
            ],
        ],
        [
            'layout' => 'section',
            'title' => 'Admin',
            'tour_key' => 'section-admin',
            'icon' => 'o-cog-6-tooth',
            'roles_any' => [Role::Admin],
            'items' => [
                ['title' => 'Kurznachrichten', 'route' => 'admin.messages.index', 'tour_key' => 'admin-messages', 'icon' => 'o-chat-bubble-left-right'],
                ['title' => 'Arbeitsgruppen', 'route' => 'arbeitsgruppen.index', 'tour_key' => 'admin-working-groups', 'icon' => 'o-rectangle-group'],
                ['title' => 'Belohnungen', 'route' => 'rewards.admin', 'tour_key' => 'admin-rewards', 'icon' => 'o-gift'],
                ['title' => 'Datenbank', 'route' => 'admin.datenbank.index', 'tour_key' => 'admin-database', 'icon' => 'o-circle-stack'],
            ],
        ],
    ],
    'guest' => [
        [
            'layout' => 'featured',
            'title' => 'Aktuelle Veranstaltung',
            'route' => 'veranstaltungen.aktuell',
            'icon' => 'o-calendar-days',
            'active_patterns' => ['veranstaltungen.*', 'fantreffen.2026*'],
            'accent' => true,
        ],
        [
            'layout' => 'featured',
            'title' => 'Aktuelle Umfrage',
            'route' => 'umfrage.aktuell',
            'icon' => 'o-chart-bar',
            'active_patterns' => ['umfrage.aktuell'],
            'visibility_flag' => 'showActivePollForGuest',
            'label_context_key' => 'activePollMenuLabel',
        ],
        [
            'layout' => 'featured',
            'title' => 'Mitglied werden',
            'route' => 'mitglied.werden',
            'icon' => 'o-user-plus',
            'active_patterns' => ['mitglied.werden*'],
        ],
        [
            'layout' => 'section',
            'title' => 'Verein',
            'icon' => 'o-building-office-2',
            'items' => [
                ['title' => 'Chronik', 'route' => 'chronik'],
                ['title' => 'Ehrenmitglieder', 'route' => 'ehrenmitglieder'],
                ['title' => 'Arbeitsgruppen', 'route' => 'arbeitsgruppen'],
                ['title' => 'Satzung', 'route' => 'satzung'],
                ['title' => 'Changelog', 'route' => 'changelog'],
            ],
        ],
        [
            'layout' => 'section',
            'title' => 'Veranstaltungen',
            'icon' => 'o-calendar',
            'items' => [
                ['title' => 'Termine', 'route' => 'termine'],
            ],
        ],
        [
            'layout' => 'section',
            'title' => 'Mitmachen',
            'icon' => 'o-heart',
            'items' => [
                ['title' => 'Spenden', 'route' => 'spenden'],
            ],
        ],
    ],
];
