name: Build and Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/mcnamara84/omxfc-vereinswebseite:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e

            cd /root/maddrax-fanclub
            
            echo "Pulling new images..."
            docker compose pull
            
            echo "Stopping containers..."
            docker compose down
            
            echo "Starting containers..."
            docker compose up -d --remove-orphans
            
            echo "Waiting for containers to start..."
            sleep 10
            
            echo "Checking container status:"
            docker ps -a
            
            echo "Waiting for database to be ready..."
            for i in {1..30}; do
              if docker exec maddrax-db mysqladmin ping -h localhost -u root -pNochSicherer456 --silent; then
                echo "Database is ready!"
                break
              fi
              echo "Waiting for database... ($i/30)"
              sleep 2
            done
            
            echo "Running Laravel setup commands..."
            # Erstelle den Storage-Link
            docker exec maddrax-app php artisan storage:link || true
            
            # Führe Migrationen aus
            if docker exec maddrax-app php artisan migrate --force; then
              echo "Migrations completed successfully"
            else
              echo "Migration failed, checking logs..."
              docker logs maddrax-app
              exit 1
            fi
            
            # Cache-Befehle
            docker exec maddrax-app php artisan config:cache
            docker exec maddrax-app php artisan route:cache
            docker exec maddrax-app php artisan view:cache
            
            # Setze Berechtigungen nochmal
            docker exec maddrax-app chown -R www-data:www-data /var/www/html/storage
            docker exec maddrax-app chmod -R 775 /var/www/html/storage
            
            echo "Final status check:"
            docker ps
            
            echo "Testing local connectivity:"
            curl -f http://localhost:8080 || echo "Local connection test failed"
            
            echo "Container logs for debugging:"
            echo "=== Nginx logs ==="
            docker logs --tail=20 maddrax-nginx
            echo "=== App logs ==="
            docker logs --tail=20 maddrax-app