name: Build and Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/mcnamara84/omxfc-vereinswebseite:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e

            cd /root/maddrax-fanclub
            docker compose pull
            docker compose down
            docker compose up -d --remove-orphans

            echo "Warte 45 Sekunden, bis DB bereit ist..."
            sleep 45

            echo "Laravel Migrationen durchführen..."
            docker exec maddrax-app php artisan migrate --force

            echo "Laravel Cache erstellen..."
            docker exec maddrax-app php artisan config:cache
            docker exec maddrax-app php artisan route:cache
            docker exec maddrax-app php artisan view:cache

            echo "Statusprüfung nach Deployment:"
            docker ps -a

            echo "Nginx-Container Logs:"
            docker logs --tail=50 maddrax-nginx

            echo "App-Container Logs:"
            docker logs --tail=50 maddrax-app
